twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        backofficeUrl: '%env(BACKOFFICE_URL)%'
    
when@test:
    twig:
        strict_variables: true
