<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220530091619 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE administrative_record_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bac_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bac_channel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bac_option_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bac_sup_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bac_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bloc_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE bloc_tag_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE campus_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE country_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE cv_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE diploma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE diploma_channel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE document_reference_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE event_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_classification_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_condition_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_language_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_room_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_session_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_session_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE exam_student_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE experience_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE faq_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE faq_topic_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE language_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE media_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE notification_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parameter_key_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parameters_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE program_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE program_channel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE refresh_tokens_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE scholar_ship_level_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE school_report_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE sport_level_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE student_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE student_diploma_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE student_workflow_history_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE administrative_record (id INT NOT NULL, exam_language_id INT DEFAULT NULL, sport_level_id INT DEFAULT NULL, scholar_ship_level_id INT DEFAULT NULL, student_id INT NOT NULL, jdc_id INT DEFAULT NULL, optional_exam_language BOOLEAN DEFAULT NULL, high_level_sportsman BOOLEAN DEFAULT NULL, third_time BOOLEAN DEFAULT NULL, scholar_ship BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_43E71B0399E217F5 ON administrative_record (exam_language_id)');
        $this->addSql('CREATE INDEX IDX_43E71B036913B41D ON administrative_record (sport_level_id)');
        $this->addSql('CREATE INDEX IDX_43E71B032CBA6114 ON administrative_record (scholar_ship_level_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_43E71B03CB944F1A ON administrative_record (student_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_43E71B03C48C18DD ON administrative_record (jdc_id)');
        $this->addSql('CREATE TABLE high_level_sportsman_medias (administrative_record_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY(administrative_record_id, media_id))');
        $this->addSql('CREATE INDEX IDX_CE6EAAAEF35FC76B ON high_level_sportsman_medias (administrative_record_id)');
        $this->addSql('CREATE INDEX IDX_CE6EAAAEEA9FDD75 ON high_level_sportsman_medias (media_id)');
        $this->addSql('CREATE TABLE third_time_medias (administrative_record_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY(administrative_record_id, media_id))');
        $this->addSql('CREATE INDEX IDX_B4A0B83F35FC76B ON third_time_medias (administrative_record_id)');
        $this->addSql('CREATE INDEX IDX_B4A0B83EA9FDD75 ON third_time_medias (media_id)');
        $this->addSql('CREATE TABLE scholar_ship_medias (administrative_record_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY(administrative_record_id, media_id))');
        $this->addSql('CREATE INDEX IDX_2330C660F35FC76B ON scholar_ship_medias (administrative_record_id)');
        $this->addSql('CREATE INDEX IDX_2330C660EA9FDD75 ON scholar_ship_medias (media_id)');
        $this->addSql('CREATE TABLE id_card_medias (administrative_record_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY(administrative_record_id, media_id))');
        $this->addSql('CREATE INDEX IDX_78FF3102F35FC76B ON id_card_medias (administrative_record_id)');
        $this->addSql('CREATE INDEX IDX_78FF3102EA9FDD75 ON id_card_medias (media_id)');
        $this->addSql('CREATE TABLE bac (id INT NOT NULL, bac_channel_id INT DEFAULT NULL, bac_option_id INT DEFAULT NULL, cv_id INT NOT NULL, media_id INT DEFAULT NULL, rewarded_year INT NOT NULL, distinction VARCHAR(50) DEFAULT NULL, detail VARCHAR(50) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1C4FAC584A986F5E ON bac (bac_channel_id)');
        $this->addSql('CREATE INDEX IDX_1C4FAC5812C82DCD ON bac (bac_option_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C4FAC58CFE419E2 ON bac (cv_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1C4FAC58EA9FDD75 ON bac (media_id)');
        $this->addSql('CREATE TABLE bac_bac_type (bac_id INT NOT NULL, bac_type_id INT NOT NULL, PRIMARY KEY(bac_id, bac_type_id))');
        $this->addSql('CREATE INDEX IDX_9F6B0198E03F15C0 ON bac_bac_type (bac_id)');
        $this->addSql('CREATE INDEX IDX_9F6B0198ECD2FEBD ON bac_bac_type (bac_type_id)');
        $this->addSql('CREATE TABLE bac_channel (id INT NOT NULL, name VARCHAR(180) NOT NULL, need_detail BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE bac_option (id INT NOT NULL, name VARCHAR(180) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE bac_option_bac_type (bac_option_id INT NOT NULL, bac_type_id INT NOT NULL, PRIMARY KEY(bac_option_id, bac_type_id))');
        $this->addSql('CREATE INDEX IDX_1F5568A112C82DCD ON bac_option_bac_type (bac_option_id)');
        $this->addSql('CREATE INDEX IDX_1F5568A1ECD2FEBD ON bac_option_bac_type (bac_type_id)');
        $this->addSql('CREATE TABLE bac_sup (id INT NOT NULL, diploma_id INT NOT NULL, diploma_channel_id INT DEFAULT NULL, cv_id INT NOT NULL, country_id INT NOT NULL, establishment VARCHAR(180) NOT NULL, year INT NOT NULL, postal_code VARCHAR(50) NOT NULL, city VARCHAR(180) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5BEB66A2A99ACEB5 ON bac_sup (diploma_id)');
        $this->addSql('CREATE INDEX IDX_5BEB66A21BDE1D70 ON bac_sup (diploma_channel_id)');
        $this->addSql('CREATE INDEX IDX_5BEB66A2CFE419E2 ON bac_sup (cv_id)');
        $this->addSql('CREATE INDEX IDX_5BEB66A2F92F3E70 ON bac_sup (country_id)');
        $this->addSql('CREATE TABLE bac_type (id INT NOT NULL, bac_channel_id INT NOT NULL, name VARCHAR(180) NOT NULL, tag VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_439492254A986F5E ON bac_type (bac_channel_id)');
        $this->addSql('CREATE TABLE bloc (id INT NOT NULL, tag_id INT NOT NULL, media_id INT DEFAULT NULL, key VARCHAR(255) DEFAULT NULL, label VARCHAR(100) DEFAULT NULL, content TEXT NOT NULL, link VARCHAR(255) DEFAULT NULL, label_link VARCHAR(100) DEFAULT NULL, position INT NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C778955A8A90ABA9 ON bloc (key)');
        $this->addSql('CREATE INDEX IDX_C778955ABAD26311 ON bloc (tag_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C778955AEA9FDD75 ON bloc (media_id)');
        $this->addSql('CREATE TABLE bloc_program_channel (bloc_id INT NOT NULL, program_channel_id INT NOT NULL, PRIMARY KEY(bloc_id, program_channel_id))');
        $this->addSql('CREATE INDEX IDX_E8E22DDF5582E9C0 ON bloc_program_channel (bloc_id)');
        $this->addSql('CREATE INDEX IDX_E8E22DDF64CF5C1E ON bloc_program_channel (program_channel_id)');
        $this->addSql('CREATE TABLE bloc_tag (id INT NOT NULL, label VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE campus (id INT NOT NULL, media_id INT DEFAULT NULL, name VARCHAR(150) NOT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, address_line3 VARCHAR(255) DEFAULT NULL, postal_code VARCHAR(25) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, country VARCHAR(150) DEFAULT NULL, email VARCHAR(255) NOT NULL, phone_reception VARCHAR(50) DEFAULT NULL, phone_customer_service VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9D0968115E237E06 ON campus (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9D096811EA9FDD75 ON campus (media_id)');
        $this->addSql('CREATE TABLE country (id INT NOT NULL, id_country VARCHAR(10) NOT NULL, name VARCHAR(180) NOT NULL, nationality VARCHAR(180) DEFAULT NULL, code_sise VARCHAR(10) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C9668DEE6016 ON country (id_country)');
        $this->addSql('CREATE TABLE cv (id INT NOT NULL, student_id INT NOT NULL, no_professional_experience BOOLEAN DEFAULT NULL, no_associative_experience BOOLEAN DEFAULT NULL, no_internationnal_experience BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B66FFE92CB944F1A ON cv (student_id)');
        $this->addSql('CREATE TABLE cv_language (cv_id INT NOT NULL, language_id INT NOT NULL, PRIMARY KEY(cv_id, language_id))');
        $this->addSql('CREATE INDEX IDX_45F49471CFE419E2 ON cv_language (cv_id)');
        $this->addSql('CREATE INDEX IDX_45F4947182F1BAF4 ON cv_language (language_id)');
        $this->addSql('CREATE TABLE diploma (id INT NOT NULL, name VARCHAR(180) NOT NULL, need_detail BOOLEAN NOT NULL, additional BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE diploma_diploma_channel (diploma_id INT NOT NULL, diploma_channel_id INT NOT NULL, PRIMARY KEY(diploma_id, diploma_channel_id))');
        $this->addSql('CREATE INDEX IDX_A1CE29BCA99ACEB5 ON diploma_diploma_channel (diploma_id)');
        $this->addSql('CREATE INDEX IDX_A1CE29BC1BDE1D70 ON diploma_diploma_channel (diploma_channel_id)');
        $this->addSql('CREATE TABLE diploma_program_channel (diploma_id INT NOT NULL, program_channel_id INT NOT NULL, PRIMARY KEY(diploma_id, program_channel_id))');
        $this->addSql('CREATE INDEX IDX_3DD599A6A99ACEB5 ON diploma_program_channel (diploma_id)');
        $this->addSql('CREATE INDEX IDX_3DD599A664CF5C1E ON diploma_program_channel (program_channel_id)');
        $this->addSql('CREATE TABLE diploma_channel (id INT NOT NULL, name VARCHAR(180) NOT NULL, need_detail BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE document_reference (id INT NOT NULL, name VARCHAR(180) NOT NULL, file VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE event (id INT NOT NULL, param_start_id INT NOT NULL, param_end_id INT DEFAULT NULL, label TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA73F77B85F ON event (param_start_id)');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7BA6DC9A6 ON event (param_end_id)');
        $this->addSql('CREATE TABLE exam_classification (id INT NOT NULL, exam_session_type_id INT NOT NULL, exam_condition_id INT NOT NULL, name VARCHAR(255) NOT NULL, need_confirmation BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DBBE3B6755022FE1 ON exam_classification (exam_session_type_id)');
        $this->addSql('CREATE INDEX IDX_DBBE3B67FF6BB08D ON exam_classification (exam_condition_id)');
        $this->addSql('CREATE TABLE exam_classification_program_channel (exam_classification_id INT NOT NULL, program_channel_id INT NOT NULL, PRIMARY KEY(exam_classification_id, program_channel_id))');
        $this->addSql('CREATE INDEX IDX_2F34B0B13BB269FD ON exam_classification_program_channel (exam_classification_id)');
        $this->addSql('CREATE INDEX IDX_2F34B0B164CF5C1E ON exam_classification_program_channel (program_channel_id)');
        $this->addSql('CREATE TABLE exam_condition (id INT NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE exam_language (id INT NOT NULL, name VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE exam_room (id INT NOT NULL, name VARCHAR(255) NOT NULL, number_of_places INT NOT NULL, third_time BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE exam_session (id INT NOT NULL, campus_id INT DEFAULT NULL, exam_classification_id INT NOT NULL, price VARCHAR(10) DEFAULT NULL, price_link VARCHAR(255) DEFAULT NULL, date_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, number_of_places INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DDE28CBCAF5D55E1 ON exam_session (campus_id)');
        $this->addSql('CREATE INDEX IDX_DDE28CBC3BB269FD ON exam_session (exam_classification_id)');
        $this->addSql('CREATE TABLE exam_session_exam_room (exam_session_id INT NOT NULL, exam_room_id INT NOT NULL, PRIMARY KEY(exam_session_id, exam_room_id))');
        $this->addSql('CREATE INDEX IDX_ADADAE407337968A ON exam_session_exam_room (exam_session_id)');
        $this->addSql('CREATE INDEX IDX_ADADAE4059B129FB ON exam_session_exam_room (exam_room_id)');
        $this->addSql('CREATE TABLE exam_session_type (id INT NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE exam_student (id INT NOT NULL, exam_session_id INT NOT NULL, student_id INT NOT NULL, exam_room_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BA85F65B7337968A ON exam_student (exam_session_id)');
        $this->addSql('CREATE INDEX IDX_BA85F65BCB944F1A ON exam_student (student_id)');
        $this->addSql('CREATE INDEX IDX_BA85F65B59B129FB ON exam_student (exam_room_id)');
        $this->addSql('CREATE TABLE experience (id INT NOT NULL, cv_id INT NOT NULL, establishment VARCHAR(180) NOT NULL, time_type VARCHAR(50) NOT NULL, begin_at DATE NOT NULL, end_at DATE DEFAULT NULL, description VARCHAR(255) NOT NULL, experience_type VARCHAR(50) NOT NULL, hours_per_week INT DEFAULT NULL, duration_in_month DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_590C103CFE419E2 ON experience (cv_id)');
        $this->addSql('CREATE TABLE faq (id INT NOT NULL, question TEXT NOT NULL, answer TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE faq_faq_topic (faq_id INT NOT NULL, faq_topic_id INT NOT NULL, PRIMARY KEY(faq_id, faq_topic_id))');
        $this->addSql('CREATE INDEX IDX_BABB232081BEC8C2 ON faq_faq_topic (faq_id)');
        $this->addSql('CREATE INDEX IDX_BABB2320E3F7D92A ON faq_faq_topic (faq_topic_id)');
        $this->addSql('CREATE TABLE faq_topic (id INT NOT NULL, label VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE faq_topic_program_channel (faq_topic_id INT NOT NULL, program_channel_id INT NOT NULL, PRIMARY KEY(faq_topic_id, program_channel_id))');
        $this->addSql('CREATE INDEX IDX_6490877BE3F7D92A ON faq_topic_program_channel (faq_topic_id)');
        $this->addSql('CREATE INDEX IDX_6490877B64CF5C1E ON faq_topic_program_channel (program_channel_id)');
        $this->addSql('CREATE TABLE language (id INT NOT NULL, code VARCHAR(3) NOT NULL, label VARCHAR(180) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE media (id INT NOT NULL, student_id INT DEFAULT NULL, file VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, state VARCHAR(255) NOT NULL, transition VARCHAR(255) DEFAULT NULL, code VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A2CA10CCB944F1A ON media (student_id)');
        $this->addSql('CREATE TABLE notification (id INT NOT NULL, parent_id INT DEFAULT NULL, sender_id UUID NOT NULL, receiver_id UUID DEFAULT NULL, roles TEXT DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, content TEXT NOT NULL, identifier VARCHAR(20) DEFAULT NULL, read BOOLEAN NOT NULL, comment VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA727ACA70 ON notification (parent_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CAF624B39D ON notification (sender_id)');
        $this->addSql('CREATE INDEX IDX_BF5476CACD53EDB6 ON notification (receiver_id)');
        $this->addSql('COMMENT ON COLUMN notification.sender_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notification.receiver_id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN notification.roles IS \'(DC2Type:array)\'');
        $this->addSql('CREATE TABLE notification_program_channel (notification_id INT NOT NULL, program_channel_id INT NOT NULL, PRIMARY KEY(notification_id, program_channel_id))');
        $this->addSql('CREATE INDEX IDX_489A6788EF1A9D84 ON notification_program_channel (notification_id)');
        $this->addSql('CREATE INDEX IDX_489A678864CF5C1E ON notification_program_channel (program_channel_id)');
        $this->addSql('CREATE TABLE parameter_key (id INT NOT NULL, name VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, format VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE parameters (id INT NOT NULL, key_id INT NOT NULL, value_string VARCHAR(255) DEFAULT NULL, value_date_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value_number INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_69348FED145533 ON parameters (key_id)');
        $this->addSql('CREATE TABLE parameter_program_channel (parameter_id INT NOT NULL, program_channel_id INT NOT NULL, PRIMARY KEY(parameter_id, program_channel_id))');
        $this->addSql('CREATE INDEX IDX_8DC4F607C56DBD6 ON parameter_program_channel (parameter_id)');
        $this->addSql('CREATE INDEX IDX_8DC4F6064CF5C1E ON parameter_program_channel (program_channel_id)');
        $this->addSql('CREATE TABLE parameter_campus (parameter_id INT NOT NULL, campus_id INT NOT NULL, PRIMARY KEY(parameter_id, campus_id))');
        $this->addSql('CREATE INDEX IDX_797762E07C56DBD6 ON parameter_campus (parameter_id)');
        $this->addSql('CREATE INDEX IDX_797762E0AF5D55E1 ON parameter_campus (campus_id)');
        $this->addSql('CREATE TABLE program (id INT NOT NULL, name VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE program_channel (id INT NOT NULL, program_id INT DEFAULT NULL, name VARCHAR(180) NOT NULL, description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_291376933EB8070A ON program_channel (program_id)');
        $this->addSql('CREATE TABLE refresh_tokens (id INT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE scholar_ship_level (id INT NOT NULL, label VARCHAR(255) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE school_report (id INT NOT NULL, media_id INT DEFAULT NULL, bac_sup_id INT NOT NULL, type VARCHAR(50) NOT NULL, score INT NOT NULL, additionnal BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39937448EA9FDD75 ON school_report (media_id)');
        $this->addSql('CREATE INDEX IDX_39937448B8C2BBB4 ON school_report (bac_sup_id)');
        $this->addSql('CREATE TABLE sport_level (id INT NOT NULL, label VARCHAR(255) NOT NULL, position INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE student (id INT NOT NULL, program_channel_id INT DEFAULT NULL, country_id INT NOT NULL, country_birth_id INT NOT NULL, nationality_id INT NOT NULL, nationality_secondary_id INT DEFAULT NULL, date_of_birth TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, state VARCHAR(255) NOT NULL, transition VARCHAR(255) DEFAULT NULL, first_name_secondary VARCHAR(255) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, identifier VARCHAR(20) NOT NULL, phone VARCHAR(20) NOT NULL, address VARCHAR(255) NOT NULL, postal_code VARCHAR(20) NOT NULL, city VARCHAR(255) NOT NULL, competition_fees_payment BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B723AF3364CF5C1E ON student (program_channel_id)');
        $this->addSql('CREATE INDEX IDX_B723AF33F92F3E70 ON student (country_id)');
        $this->addSql('CREATE INDEX IDX_B723AF33F722092F ON student (country_birth_id)');
        $this->addSql('CREATE INDEX IDX_B723AF331C9DA55 ON student (nationality_id)');
        $this->addSql('CREATE INDEX IDX_B723AF3315BED435 ON student (nationality_secondary_id)');
        $this->addSql('CREATE TABLE student_diploma (id INT NOT NULL, diploma_channel_id INT DEFAULT NULL, diploma_id INT NOT NULL, administrative_record_id INT DEFAULT NULL, year INT NOT NULL, establishment VARCHAR(180) NOT NULL, postal_code VARCHAR(50) NOT NULL, city VARCHAR(180) NOT NULL, detail VARCHAR(180) DEFAULT NULL, last_diploma BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1173CAF1BDE1D70 ON student_diploma (diploma_channel_id)');
        $this->addSql('CREATE INDEX IDX_1173CAFA99ACEB5 ON student_diploma (diploma_id)');
        $this->addSql('CREATE INDEX IDX_1173CAFF35FC76B ON student_diploma (administrative_record_id)');
        $this->addSql('CREATE TABLE student_diploma_media (student_diploma_id INT NOT NULL, media_id INT NOT NULL, PRIMARY KEY(student_diploma_id, media_id))');
        $this->addSql('CREATE INDEX IDX_A083BE3D44452354 ON student_diploma_media (student_diploma_id)');
        $this->addSql('CREATE INDEX IDX_A083BE3DEA9FDD75 ON student_diploma_media (media_id)');
        $this->addSql('CREATE TABLE student_workflow_history (id INT NOT NULL, student_id INT DEFAULT NULL, state VARCHAR(255) NOT NULL, transition VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F7A7C78ECB944F1A ON student_workflow_history (student_id)');
        $this->addSql('CREATE TABLE users (id UUID NOT NULL, student_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles TEXT NOT NULL, plain_password VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(180) NOT NULL, last_name VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9CB944F1A ON users (student_id)');
        $this->addSql('COMMENT ON COLUMN users.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN users.roles IS \'(DC2Type:array)\'');
        $this->addSql('ALTER TABLE administrative_record ADD CONSTRAINT FK_43E71B0399E217F5 FOREIGN KEY (exam_language_id) REFERENCES exam_language (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE administrative_record ADD CONSTRAINT FK_43E71B036913B41D FOREIGN KEY (sport_level_id) REFERENCES sport_level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE administrative_record ADD CONSTRAINT FK_43E71B032CBA6114 FOREIGN KEY (scholar_ship_level_id) REFERENCES scholar_ship_level (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE administrative_record ADD CONSTRAINT FK_43E71B03CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE administrative_record ADD CONSTRAINT FK_43E71B03C48C18DD FOREIGN KEY (jdc_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE high_level_sportsman_medias ADD CONSTRAINT FK_CE6EAAAEF35FC76B FOREIGN KEY (administrative_record_id) REFERENCES administrative_record (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE high_level_sportsman_medias ADD CONSTRAINT FK_CE6EAAAEEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE third_time_medias ADD CONSTRAINT FK_B4A0B83F35FC76B FOREIGN KEY (administrative_record_id) REFERENCES administrative_record (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE third_time_medias ADD CONSTRAINT FK_B4A0B83EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE scholar_ship_medias ADD CONSTRAINT FK_2330C660F35FC76B FOREIGN KEY (administrative_record_id) REFERENCES administrative_record (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE scholar_ship_medias ADD CONSTRAINT FK_2330C660EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE id_card_medias ADD CONSTRAINT FK_78FF3102F35FC76B FOREIGN KEY (administrative_record_id) REFERENCES administrative_record (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE id_card_medias ADD CONSTRAINT FK_78FF3102EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac ADD CONSTRAINT FK_1C4FAC584A986F5E FOREIGN KEY (bac_channel_id) REFERENCES bac_channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac ADD CONSTRAINT FK_1C4FAC5812C82DCD FOREIGN KEY (bac_option_id) REFERENCES bac_option (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac ADD CONSTRAINT FK_1C4FAC58CFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac ADD CONSTRAINT FK_1C4FAC58EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_bac_type ADD CONSTRAINT FK_9F6B0198E03F15C0 FOREIGN KEY (bac_id) REFERENCES bac (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_bac_type ADD CONSTRAINT FK_9F6B0198ECD2FEBD FOREIGN KEY (bac_type_id) REFERENCES bac_type (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_option_bac_type ADD CONSTRAINT FK_1F5568A112C82DCD FOREIGN KEY (bac_option_id) REFERENCES bac_option (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_option_bac_type ADD CONSTRAINT FK_1F5568A1ECD2FEBD FOREIGN KEY (bac_type_id) REFERENCES bac_type (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_sup ADD CONSTRAINT FK_5BEB66A2A99ACEB5 FOREIGN KEY (diploma_id) REFERENCES diploma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_sup ADD CONSTRAINT FK_5BEB66A21BDE1D70 FOREIGN KEY (diploma_channel_id) REFERENCES diploma_channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_sup ADD CONSTRAINT FK_5BEB66A2CFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_sup ADD CONSTRAINT FK_5BEB66A2F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bac_type ADD CONSTRAINT FK_439492254A986F5E FOREIGN KEY (bac_channel_id) REFERENCES bac_channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bloc ADD CONSTRAINT FK_C778955ABAD26311 FOREIGN KEY (tag_id) REFERENCES bloc_tag (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bloc ADD CONSTRAINT FK_C778955AEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bloc_program_channel ADD CONSTRAINT FK_E8E22DDF5582E9C0 FOREIGN KEY (bloc_id) REFERENCES bloc (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE bloc_program_channel ADD CONSTRAINT FK_E8E22DDF64CF5C1E FOREIGN KEY (program_channel_id) REFERENCES program_channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE campus ADD CONSTRAINT FK_9D096811EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_B66FFE92CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cv_language ADD CONSTRAINT FK_45F49471CFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cv_language ADD CONSTRAINT FK_45F4947182F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE diploma_diploma_channel ADD CONSTRAINT FK_A1CE29BCA99ACEB5 FOREIGN KEY (diploma_id) REFERENCES diploma (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE diploma_diploma_channel ADD CONSTRAINT FK_A1CE29BC1BDE1D70 FOREIGN KEY (diploma_channel_id) REFERENCES diploma_channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE diploma_program_channel ADD CONSTRAINT FK_3DD599A6A99ACEB5 FOREIGN KEY (diploma_id) REFERENCES diploma (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE diploma_program_channel ADD CONSTRAINT FK_3DD599A664CF5C1E FOREIGN KEY (program_channel_id) REFERENCES program_channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA73F77B85F FOREIGN KEY (param_start_id) REFERENCES parameters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7BA6DC9A6 FOREIGN KEY (param_end_id) REFERENCES parameters (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_classification ADD CONSTRAINT FK_DBBE3B6755022FE1 FOREIGN KEY (exam_session_type_id) REFERENCES exam_session_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_classification ADD CONSTRAINT FK_DBBE3B67FF6BB08D FOREIGN KEY (exam_condition_id) REFERENCES exam_condition (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_classification_program_channel ADD CONSTRAINT FK_2F34B0B13BB269FD FOREIGN KEY (exam_classification_id) REFERENCES exam_classification (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_classification_program_channel ADD CONSTRAINT FK_2F34B0B164CF5C1E FOREIGN KEY (program_channel_id) REFERENCES program_channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_session ADD CONSTRAINT FK_DDE28CBCAF5D55E1 FOREIGN KEY (campus_id) REFERENCES campus (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_session ADD CONSTRAINT FK_DDE28CBC3BB269FD FOREIGN KEY (exam_classification_id) REFERENCES exam_classification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_session_exam_room ADD CONSTRAINT FK_ADADAE407337968A FOREIGN KEY (exam_session_id) REFERENCES exam_session (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_session_exam_room ADD CONSTRAINT FK_ADADAE4059B129FB FOREIGN KEY (exam_room_id) REFERENCES exam_room (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_student ADD CONSTRAINT FK_BA85F65B7337968A FOREIGN KEY (exam_session_id) REFERENCES exam_session (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_student ADD CONSTRAINT FK_BA85F65BCB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE exam_student ADD CONSTRAINT FK_BA85F65B59B129FB FOREIGN KEY (exam_room_id) REFERENCES exam_room (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience ADD CONSTRAINT FK_590C103CFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faq_faq_topic ADD CONSTRAINT FK_BABB232081BEC8C2 FOREIGN KEY (faq_id) REFERENCES faq (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faq_faq_topic ADD CONSTRAINT FK_BABB2320E3F7D92A FOREIGN KEY (faq_topic_id) REFERENCES faq_topic (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faq_topic_program_channel ADD CONSTRAINT FK_6490877BE3F7D92A FOREIGN KEY (faq_topic_id) REFERENCES faq_topic (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE faq_topic_program_channel ADD CONSTRAINT FK_6490877B64CF5C1E FOREIGN KEY (program_channel_id) REFERENCES program_channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE media ADD CONSTRAINT FK_6A2CA10CCB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA727ACA70 FOREIGN KEY (parent_id) REFERENCES notification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAF624B39D FOREIGN KEY (sender_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CACD53EDB6 FOREIGN KEY (receiver_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_program_channel ADD CONSTRAINT FK_489A6788EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_program_channel ADD CONSTRAINT FK_489A678864CF5C1E FOREIGN KEY (program_channel_id) REFERENCES program_channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parameters ADD CONSTRAINT FK_69348FED145533 FOREIGN KEY (key_id) REFERENCES parameter_key (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parameter_program_channel ADD CONSTRAINT FK_8DC4F607C56DBD6 FOREIGN KEY (parameter_id) REFERENCES parameters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parameter_program_channel ADD CONSTRAINT FK_8DC4F6064CF5C1E FOREIGN KEY (program_channel_id) REFERENCES program_channel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parameter_campus ADD CONSTRAINT FK_797762E07C56DBD6 FOREIGN KEY (parameter_id) REFERENCES parameters (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE parameter_campus ADD CONSTRAINT FK_797762E0AF5D55E1 FOREIGN KEY (campus_id) REFERENCES campus (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE program_channel ADD CONSTRAINT FK_291376933EB8070A FOREIGN KEY (program_id) REFERENCES program (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE school_report ADD CONSTRAINT FK_39937448EA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE school_report ADD CONSTRAINT FK_39937448B8C2BBB4 FOREIGN KEY (bac_sup_id) REFERENCES bac_sup (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF3364CF5C1E FOREIGN KEY (program_channel_id) REFERENCES program_channel (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33F722092F FOREIGN KEY (country_birth_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF331C9DA55 FOREIGN KEY (nationality_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF3315BED435 FOREIGN KEY (nationality_secondary_id) REFERENCES country (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_diploma ADD CONSTRAINT FK_1173CAF1BDE1D70 FOREIGN KEY (diploma_channel_id) REFERENCES diploma_channel (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_diploma ADD CONSTRAINT FK_1173CAFA99ACEB5 FOREIGN KEY (diploma_id) REFERENCES diploma (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_diploma ADD CONSTRAINT FK_1173CAFF35FC76B FOREIGN KEY (administrative_record_id) REFERENCES administrative_record (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_diploma_media ADD CONSTRAINT FK_A083BE3D44452354 FOREIGN KEY (student_diploma_id) REFERENCES student_diploma (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_diploma_media ADD CONSTRAINT FK_A083BE3DEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_workflow_history ADD CONSTRAINT FK_F7A7C78ECB944F1A FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E9CB944F1A FOREIGN KEY (student_id) REFERENCES student (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE high_level_sportsman_medias DROP CONSTRAINT FK_CE6EAAAEF35FC76B');
        $this->addSql('ALTER TABLE third_time_medias DROP CONSTRAINT FK_B4A0B83F35FC76B');
        $this->addSql('ALTER TABLE scholar_ship_medias DROP CONSTRAINT FK_2330C660F35FC76B');
        $this->addSql('ALTER TABLE id_card_medias DROP CONSTRAINT FK_78FF3102F35FC76B');
        $this->addSql('ALTER TABLE student_diploma DROP CONSTRAINT FK_1173CAFF35FC76B');
        $this->addSql('ALTER TABLE bac_bac_type DROP CONSTRAINT FK_9F6B0198E03F15C0');
        $this->addSql('ALTER TABLE bac DROP CONSTRAINT FK_1C4FAC584A986F5E');
        $this->addSql('ALTER TABLE bac_type DROP CONSTRAINT FK_439492254A986F5E');
        $this->addSql('ALTER TABLE bac DROP CONSTRAINT FK_1C4FAC5812C82DCD');
        $this->addSql('ALTER TABLE bac_option_bac_type DROP CONSTRAINT FK_1F5568A112C82DCD');
        $this->addSql('ALTER TABLE school_report DROP CONSTRAINT FK_39937448B8C2BBB4');
        $this->addSql('ALTER TABLE bac_bac_type DROP CONSTRAINT FK_9F6B0198ECD2FEBD');
        $this->addSql('ALTER TABLE bac_option_bac_type DROP CONSTRAINT FK_1F5568A1ECD2FEBD');
        $this->addSql('ALTER TABLE bloc_program_channel DROP CONSTRAINT FK_E8E22DDF5582E9C0');
        $this->addSql('ALTER TABLE bloc DROP CONSTRAINT FK_C778955ABAD26311');
        $this->addSql('ALTER TABLE exam_session DROP CONSTRAINT FK_DDE28CBCAF5D55E1');
        $this->addSql('ALTER TABLE parameter_campus DROP CONSTRAINT FK_797762E0AF5D55E1');
        $this->addSql('ALTER TABLE bac_sup DROP CONSTRAINT FK_5BEB66A2F92F3E70');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33F92F3E70');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33F722092F');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF331C9DA55');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF3315BED435');
        $this->addSql('ALTER TABLE bac DROP CONSTRAINT FK_1C4FAC58CFE419E2');
        $this->addSql('ALTER TABLE bac_sup DROP CONSTRAINT FK_5BEB66A2CFE419E2');
        $this->addSql('ALTER TABLE cv_language DROP CONSTRAINT FK_45F49471CFE419E2');
        $this->addSql('ALTER TABLE experience DROP CONSTRAINT FK_590C103CFE419E2');
        $this->addSql('ALTER TABLE bac_sup DROP CONSTRAINT FK_5BEB66A2A99ACEB5');
        $this->addSql('ALTER TABLE diploma_diploma_channel DROP CONSTRAINT FK_A1CE29BCA99ACEB5');
        $this->addSql('ALTER TABLE diploma_program_channel DROP CONSTRAINT FK_3DD599A6A99ACEB5');
        $this->addSql('ALTER TABLE student_diploma DROP CONSTRAINT FK_1173CAFA99ACEB5');
        $this->addSql('ALTER TABLE bac_sup DROP CONSTRAINT FK_5BEB66A21BDE1D70');
        $this->addSql('ALTER TABLE diploma_diploma_channel DROP CONSTRAINT FK_A1CE29BC1BDE1D70');
        $this->addSql('ALTER TABLE student_diploma DROP CONSTRAINT FK_1173CAF1BDE1D70');
        $this->addSql('ALTER TABLE exam_classification_program_channel DROP CONSTRAINT FK_2F34B0B13BB269FD');
        $this->addSql('ALTER TABLE exam_session DROP CONSTRAINT FK_DDE28CBC3BB269FD');
        $this->addSql('ALTER TABLE exam_classification DROP CONSTRAINT FK_DBBE3B67FF6BB08D');
        $this->addSql('ALTER TABLE administrative_record DROP CONSTRAINT FK_43E71B0399E217F5');
        $this->addSql('ALTER TABLE exam_session_exam_room DROP CONSTRAINT FK_ADADAE4059B129FB');
        $this->addSql('ALTER TABLE exam_student DROP CONSTRAINT FK_BA85F65B59B129FB');
        $this->addSql('ALTER TABLE exam_session_exam_room DROP CONSTRAINT FK_ADADAE407337968A');
        $this->addSql('ALTER TABLE exam_student DROP CONSTRAINT FK_BA85F65B7337968A');
        $this->addSql('ALTER TABLE exam_classification DROP CONSTRAINT FK_DBBE3B6755022FE1');
        $this->addSql('ALTER TABLE faq_faq_topic DROP CONSTRAINT FK_BABB232081BEC8C2');
        $this->addSql('ALTER TABLE faq_faq_topic DROP CONSTRAINT FK_BABB2320E3F7D92A');
        $this->addSql('ALTER TABLE faq_topic_program_channel DROP CONSTRAINT FK_6490877BE3F7D92A');
        $this->addSql('ALTER TABLE cv_language DROP CONSTRAINT FK_45F4947182F1BAF4');
        $this->addSql('ALTER TABLE administrative_record DROP CONSTRAINT FK_43E71B03C48C18DD');
        $this->addSql('ALTER TABLE high_level_sportsman_medias DROP CONSTRAINT FK_CE6EAAAEEA9FDD75');
        $this->addSql('ALTER TABLE third_time_medias DROP CONSTRAINT FK_B4A0B83EA9FDD75');
        $this->addSql('ALTER TABLE scholar_ship_medias DROP CONSTRAINT FK_2330C660EA9FDD75');
        $this->addSql('ALTER TABLE id_card_medias DROP CONSTRAINT FK_78FF3102EA9FDD75');
        $this->addSql('ALTER TABLE bac DROP CONSTRAINT FK_1C4FAC58EA9FDD75');
        $this->addSql('ALTER TABLE bloc DROP CONSTRAINT FK_C778955AEA9FDD75');
        $this->addSql('ALTER TABLE campus DROP CONSTRAINT FK_9D096811EA9FDD75');
        $this->addSql('ALTER TABLE school_report DROP CONSTRAINT FK_39937448EA9FDD75');
        $this->addSql('ALTER TABLE student_diploma_media DROP CONSTRAINT FK_A083BE3DEA9FDD75');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA727ACA70');
        $this->addSql('ALTER TABLE notification_program_channel DROP CONSTRAINT FK_489A6788EF1A9D84');
        $this->addSql('ALTER TABLE parameters DROP CONSTRAINT FK_69348FED145533');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA73F77B85F');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7BA6DC9A6');
        $this->addSql('ALTER TABLE parameter_program_channel DROP CONSTRAINT FK_8DC4F607C56DBD6');
        $this->addSql('ALTER TABLE parameter_campus DROP CONSTRAINT FK_797762E07C56DBD6');
        $this->addSql('ALTER TABLE program_channel DROP CONSTRAINT FK_291376933EB8070A');
        $this->addSql('ALTER TABLE bloc_program_channel DROP CONSTRAINT FK_E8E22DDF64CF5C1E');
        $this->addSql('ALTER TABLE diploma_program_channel DROP CONSTRAINT FK_3DD599A664CF5C1E');
        $this->addSql('ALTER TABLE exam_classification_program_channel DROP CONSTRAINT FK_2F34B0B164CF5C1E');
        $this->addSql('ALTER TABLE faq_topic_program_channel DROP CONSTRAINT FK_6490877B64CF5C1E');
        $this->addSql('ALTER TABLE notification_program_channel DROP CONSTRAINT FK_489A678864CF5C1E');
        $this->addSql('ALTER TABLE parameter_program_channel DROP CONSTRAINT FK_8DC4F6064CF5C1E');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF3364CF5C1E');
        $this->addSql('ALTER TABLE administrative_record DROP CONSTRAINT FK_43E71B032CBA6114');
        $this->addSql('ALTER TABLE administrative_record DROP CONSTRAINT FK_43E71B036913B41D');
        $this->addSql('ALTER TABLE administrative_record DROP CONSTRAINT FK_43E71B03CB944F1A');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE92CB944F1A');
        $this->addSql('ALTER TABLE exam_student DROP CONSTRAINT FK_BA85F65BCB944F1A');
        $this->addSql('ALTER TABLE media DROP CONSTRAINT FK_6A2CA10CCB944F1A');
        $this->addSql('ALTER TABLE student_workflow_history DROP CONSTRAINT FK_F7A7C78ECB944F1A');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E9CB944F1A');
        $this->addSql('ALTER TABLE student_diploma_media DROP CONSTRAINT FK_A083BE3D44452354');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAF624B39D');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CACD53EDB6');
        $this->addSql('DROP SEQUENCE administrative_record_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bac_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bac_channel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bac_option_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bac_sup_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bac_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bloc_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE bloc_tag_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE campus_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE country_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE cv_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE diploma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE diploma_channel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE document_reference_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE event_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_classification_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_condition_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_language_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_room_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_session_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_session_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE exam_student_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE experience_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE faq_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE faq_topic_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE language_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE media_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE notification_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parameter_key_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parameters_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE program_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE program_channel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE refresh_tokens_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE scholar_ship_level_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE school_report_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE sport_level_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE student_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE student_diploma_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE student_workflow_history_id_seq CASCADE');
        $this->addSql('DROP TABLE administrative_record');
        $this->addSql('DROP TABLE high_level_sportsman_medias');
        $this->addSql('DROP TABLE third_time_medias');
        $this->addSql('DROP TABLE scholar_ship_medias');
        $this->addSql('DROP TABLE id_card_medias');
        $this->addSql('DROP TABLE bac');
        $this->addSql('DROP TABLE bac_bac_type');
        $this->addSql('DROP TABLE bac_channel');
        $this->addSql('DROP TABLE bac_option');
        $this->addSql('DROP TABLE bac_option_bac_type');
        $this->addSql('DROP TABLE bac_sup');
        $this->addSql('DROP TABLE bac_type');
        $this->addSql('DROP TABLE bloc');
        $this->addSql('DROP TABLE bloc_program_channel');
        $this->addSql('DROP TABLE bloc_tag');
        $this->addSql('DROP TABLE campus');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE cv');
        $this->addSql('DROP TABLE cv_language');
        $this->addSql('DROP TABLE diploma');
        $this->addSql('DROP TABLE diploma_diploma_channel');
        $this->addSql('DROP TABLE diploma_program_channel');
        $this->addSql('DROP TABLE diploma_channel');
        $this->addSql('DROP TABLE document_reference');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE exam_classification');
        $this->addSql('DROP TABLE exam_classification_program_channel');
        $this->addSql('DROP TABLE exam_condition');
        $this->addSql('DROP TABLE exam_language');
        $this->addSql('DROP TABLE exam_room');
        $this->addSql('DROP TABLE exam_session');
        $this->addSql('DROP TABLE exam_session_exam_room');
        $this->addSql('DROP TABLE exam_session_type');
        $this->addSql('DROP TABLE exam_student');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE faq_faq_topic');
        $this->addSql('DROP TABLE faq_topic');
        $this->addSql('DROP TABLE faq_topic_program_channel');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE media');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_program_channel');
        $this->addSql('DROP TABLE parameter_key');
        $this->addSql('DROP TABLE parameters');
        $this->addSql('DROP TABLE parameter_program_channel');
        $this->addSql('DROP TABLE parameter_campus');
        $this->addSql('DROP TABLE program');
        $this->addSql('DROP TABLE program_channel');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE scholar_ship_level');
        $this->addSql('DROP TABLE school_report');
        $this->addSql('DROP TABLE sport_level');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE student_diploma');
        $this->addSql('DROP TABLE student_diploma_media');
        $this->addSql('DROP TABLE student_workflow_history');
        $this->addSql('DROP TABLE users');
    }
}
