services:
  _defaults:
    autowire: true
    autoconfigure: true

  monolog.gelf_handler:
    class: Monolog\Handler\GelfHandler
    arguments:
      - "@gelf.publisher"
      - 'error' #monolog config is ignored with custom service level has to be redefined here (default : debug), you should probably use parameters eg: '%gelf_level%'

  gelf.publisher:
    class: Gelf\Publisher
    arguments: [ "@gelf.ignore_error_transport" ]

  gelf.ignore_error_transport:
    class: Gelf\Transport\IgnoreErrorTransportWrapper
    arguments: [ "@gelf.transport" ]

  gelf.transport:
    class: Gelf\Transport\UdpTransport # or Tcp, Amp, Http,...
    arguments:
      - "logstash"