parameters:
  medias_private_path: 'private/medias'
  medias_fixture_path: 'public/fixtures'
  document_reference_directory: 'documents/document_reference/'
  locale: fr
  reset_password_url: '%env(resolve:RESET_PASSWORD_URL)%'
  account_activation_url: '%env(resolve:ACCOUNT_ACTIVATION_URL)%'
  backoffice_url: '%env(resolve:BACKOFFICE_URL)%'
  email: '%env(resolve:EMAIL)%'
  email_sc: '%env(resolve:EMAIL_SC)%'
  app_name: '%env(resolve:APP_NAME)%'
  app_version: '%env(resolve:APP_VERSION)%'
  app_descripion: '%env(resolve:APP_DESCRIPION)%'
  payment_merchant_id: '%env(resolve:PAYMENT_MERCHANT_ID)%'
  payment_api_key: '%env(resolve:PAYMENT_API_KEY)%'
  payment_api_secret: '%env(resolve:PAYMENT_API_SECRET)%'
  payment_api_endpoint: '%env(resolve:PAYMENT_API_ENDPOINT)%'
  payment_integrator: '%env(resolve:PAYMENT_INTEGRATOR)%'
  payment_webhook_token: '%env(resolve:PAYMENT_WEBHOOK_TOKEN)%'
  export_private_path: '%kernel.project_dir%/private/export'
  supervision_sender: '%env(resolve:SUPERVISION_SENDER)%'
  supervision_mail: '%env(resolve:SUPERVISION_MAIL)%'
  admissibility_landing_url: '%env(resolve:ADMISSIBILITY_LANDING_URL)%'
